### ISSUE TITLE
Fail to update all releases

### ISSUE THREAD

**Issue by cpolcyn** [SalesforceFoundation/statusite#22]
Currently every time this job runs it fails with the same error. It manages to reload 10 releases before hitting this.

```bash
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.5/site-packages/rq/worker.py", line 710, in perform_job
    rv = job.perform()
  File "/app/.heroku/python/lib/python3.5/site-packages/rq/job.py", line 560, in perform
    self._result = self._execute()
  File "/app/.heroku/python/lib/python3.5/site-packages/rq/job.py", line 566, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/app/statusite/repository/tasks.py", line 22, in update_latest_releases
    reload_releases(repo.releases)
  File "/app/statusite/repository/tasks.py", line 19, in reload_releases
    release.reload()
  File "/app/statusite/repository/models.py", line 91, in reload
    'release: {}'.format(release)
statusite.repository.exceptions.RepoReloadError: 
GitHub repo: https://github.com/SalesforceFoundation/Cumulus
GitHub release ID: 7576954
release: None
```

**Comment by cpolcyn** [comment]
This is related to https://github.com/SalesforceFoundation/statusite/issues/10

I created a release in Cumulus but later deleted it and replaced it, so the release ID was no longer valid. If we reuse the Release object we can update the ID.

For now I have worked around by deleting the outdated object in the db.
